# Generated by Django 3.1.5 on 2021-04-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('text', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('date', models.DateField(default=None, null=True, verbose_name='Дата')),
                ('days', models.IntegerField(default=0, verbose_name='Количество дней выполнения')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=0, verbose_name='Долгота')),
                ('latitude', models.FloatField(default=0, verbose_name='Широта')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('url', models.CharField(default='', max_length=1000, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('status', models.CharField(choices=[('1', 'Всё нормально'), ('2', 'Сервер лежит'), ('3', 'Активные заявки'), ('4', 'Горящие заявки'), ('5', 'Проблемы с системой интеграции'), ('6', 'Предупреждение')], default='1', max_length=100)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='ClientAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
    ]
